### ISSUE TITLE
X11 error / GPU failed to acquire a swapchain frame

### ISSUE THREAD

**Issue by tato** [parasyte/pixels#135]
Running 'minimal-winit' example on Ubuntu 20.04. This is the logs I get to stdout.

```
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[2021-02-05T13:58:08Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
[2021-02-05T13:58:08Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
[2021-02-05T13:58:08Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
[2021-02-05T13:58:08Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
[2021-02-05T13:58:08Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
[2021-02-05T13:58:08Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
[2021-02-05T13:58:09Z ERROR minimal_winit] pixels.render() failed: The GPU failed to acquire a swapchain frame.
```

The window doesn't render anything and stays completely black. Also doesn't respond to any input, nor does it close when the X button is pressed. When the window is resized, it closes / crashes with no log to stdout.

**Comment by bjorn3** [comment]
This is probably an issue with [winit](https://github.com/rust-windowing/winit/). Can you try one of their examples?

**Comment by tato** [comment]
I don't see anything wrong when I run their examples

**Comment by parasyte** [comment]
@tato You may also want to try the `wgpu` examples and then the `gfx` examples:

* https://github.com/gfx-rs/wgpu-rs/tree/master/examples
* https://github.com/gfx-rs/gfx/tree/master/examples

Honestly, I don't know if you will have any luck running anything on Intel. The GPU driver may be out of date, or you might just have better luck switching to a higher performance GPU (assuming you have one) by following the [troubleshooting instructions](https://github.com/parasyte/pixels#troubleshooting).

**Comment by tato** [comment]
I do get the same error with wgpu. Personally it's not a big deal because it's not my primary machine. Thanks for the attention.

**Comment by parasyte** [comment]
This is now a very old issue, and with no other reports or information, I don't think there is anything actionable here.
