### ISSUE TITLE
'Use of unstable library feature 'wake_trait'' in Dear Imgui example

### ISSUE THREAD

**Issue by alexanderameye** [parasyte/pixels#161]
I'm looking at the DearImgui example project but I get compilation errors with the 'pollster' dependency.  Is this something you encountered as well? I'm quite new to Rust so possibly/probably this is unrelated to Pixels itself...

Thanks in advance :)

![image](https://user-images.githubusercontent.com/5512569/117341790-d4058a80-aea2-11eb-8fc5-68b5ab004de5.png)

**Comment by alexanderameye** [comment]
I guess I wasn't on Rust 1.51 which introduced the stable version of the wake trait I see. My bad, should've read the docs better!

**Comment by parasyte** [comment]
That's right. I don't know when (or how) this was broken by 1.50, since it used to work. But they did it! Updating the compiler is the solution.
