### ISSUE TITLE
reference for imgui-winit needs refreshing?

### ISSUE THREAD

**Issue by meshula** [parasyte/pixels#193]
I think the reference for imgui-winit needs refreshing as it refers to a now unexisting imgui-wgpu hash? 

```sh
pi@raspberrypi:~/dev/pixels/examples/invaders $ cargo run --release --package invaders
    Updating crates.io index
    Updating git repository `https://github.com/kylc/imgui-wgpu-rs.git`
error: failed to get `imgui-wgpu` as a dependency of package `imgui-winit v0.1.0 (/home/pi/dev/pixels/examples/imgui-winit)`

Caused by:
  failed to load source for dependency `imgui-wgpu`

Caused by:
  Unable to update https://github.com/kylc/imgui-wgpu-rs.git?rev=fbbc0cfc7de25a4821980cb2170195c7b3b0fcf4
```

**Comment by parasyte** [comment]
This was changed yesterday as part of the update to `wgpu` 0.10: #185 This example is currently based on an open PR that is still a moving target. I tried to prevent build breakage by pinning the git revision, but it appears they deleted the rev with a `force-push`.

**Comment by parasyte** [comment]
Hmmm, nope, I'm wrong. I just deleted my local `Cargo.lock` and I'm still able to build and run the `imgui-winit` example without changing anything else.

The command you pasted wasn't even running the imgui example. @meshula What version of Rust/cargo are you using? We have a policy tracking the minimum supported version: https://github.com/parasyte/pixels/blob/master/MSRV.md Please ensure you are using a supported compiler. I personally just tested every stable version since 1.52.0, and they can all build the `invaders` package from a clean copy of the repo.

The commit referenced is definitely still valid: https://github.com/kylc/imgui-wgpu-rs/commit/fbbc0cfc7de25a4821980cb2170195c7b3b0fcf4 The only thing I can think of is that your Cargo/rustc version must be out of date.

**Comment by meshula** [comment]
Here were my steps, looking at my history:

> The command you pasted wasn't even running the imgui example.

That's correct, I was trying to run the invaders example, which resulted in the imgui-wgpu error.

1) create new flash card with latest Debian Buster, 64 bits, start rpi, do the usual set up rigamarole.
2) open terminal
3) installed typical dev essentials things, probably completely unnecessary and unrelated to this problem
4) per rustlang.org `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
5) open new terminal so that Rust is in $PATH
6) rustc says 1.54.0, cargo says 1.54.0
7) `mkdir ~/dev;cd ~/dev`
8) `git clone https://github.com/parasyte/pixels.git;cd pixels`
9) `cd examples/invaders`
10) `cargo run --release --package invaders`
11) The diagnostic I pasted in the first message resulted.

As a check, I went to a Mac that has a well-exercised Rust installation, and attempted a repro:

```sh
╰─ rustc --version
rustc 1.52.1 (9bc8c42bb 2021-05-09)

╰─ git clone https://github.com/parasyte/pixels.git;cd pixels 
Cloning into 'pixels'...
remote: Enumerating objects: 1469, done.
remote: Counting objects: 100% (313/313), done.
remote: Compressing objects: 100% (199/199), done.
remote: Total 1469 (delta 159), reused 216 (delta 100), pack-reused 1156
Receiving objects: 100% (1469/1469), 4.03 MiB | 4.81 MiB/s, done.
Resolving deltas: 100% (754/754), done.

╰─ cd examples/invaders

╰─ cargo run --release --package invaders
    Updating crates.io index
    Updating git repository `https://github.com/kylc/imgui-wgpu-rs.git`
error: failed to get `imgui-wgpu` as a dependency of package `imgui-winit v0.1.0 (/Users/nporcino/dev/pixels/examples/imgui-winit)`

Caused by:
  failed to load source for dependency `imgui-wgpu`

Caused by:
  Unable to update https://github.com/kylc/imgui-wgpu-rs.git?rev=fbbc0cfc7de25a4821980cb2170195c7b3b0fcf4

Caused by:
  revspec 'fbbc0cfc7de25a4821980cb2170195c7b3b0fcf4' not found; class=Reference (4); code=NotFound (-3)
```

If there's anything I can try at my end, I'm happy to attempt and post results.

**Comment by parasyte** [comment]
😖 Well the obvious thing to try is changing the revision to the latest: `a153c00d81db7812a1b4621ad9a0e8fd34a17610` or even just switching to the branch name:

```patch
diff --git a/examples/imgui-winit/Cargo.toml b/examples/imgui-winit/Cargo.toml
index 69a270a..d7c15e9 100644
--- a/examples/imgui-winit/Cargo.toml
+++ b/examples/imgui-winit/Cargo.toml
@@ -13,7 +13,7 @@ default = ["optimize"]
 [dependencies]
 env_logger = "0.9"
 imgui = "0.7"
-imgui-wgpu = { git = "https://github.com/kylc/imgui-wgpu-rs.git", rev = "fbbc0cfc7de25a4821980cb2170195c7b3b0fcf4" }
+imgui-wgpu = { git = "https://github.com/kylc/imgui-wgpu-rs.git", branch = "wgpu-0.10" }
 imgui-winit-support = { version = "0.7.1", default-features = false, features = ["winit-25"] }
 log = "0.4"
 pixels = { path = "../.." }
```

**Comment by meshula** [comment]
I thought of that at the same time based on your PR comment, and tried it, it works, using the SHA a153c00d81db7812a1b4621ad9a0e8fd34a17610 :) TIL I learned how to troubleshoot Cargo.toml references!

**Comment by meshula** [comment]
FWIW just to confirm, the branch version you suggest worked as well, just tried it, although I'm sure you already knew it would.

**Comment by parasyte** [comment]
Ok, I've opened a PR with the patch I provided above. That should prevent the issue - whatever it is - for other users.
