### ISSUE TITLE
STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by Lucky4Luuk** [parasyte/pixels#234]
Library versions:
pixels = "0.8.0"
winit = "0.26.0" (also tested 0.25.0, just in case)

WGPU ends up throwing a STATUS_ACCESS_VIOLATION whenever I run my (simple) program on my laptop's iGPU (Intel UHD 620).
Issue does not occur on my pc's GTX1080. I would try an example, but `minimal-winit` does not compile (it can't find `winapi_util`)

Full debug log: https://paste.myst.rs/yliquz2g

Do you think this is an issue with WGPU or pixels?

**Comment by parasyte** [comment]
My best guess is that you are hitting a bug in the Intel Vulkan driver. Here are some similar reports for reference:

- #49
- https://github.com/gfx-rs/gfx/issues/3128

My suggestion would be writing down the version number you currently have installed for the driver and reporting it on that `wgpu` issue. Then upgrade the driver and that might be enough to fix it.

The other thing about `winapi_util` is weird. I haven't seen or heard of that issue before. I cannot reproduce the error on Windows 11. The only reference to `winapi-util` in the dependency tree is from `evn_logger`:

```
$ cargo tree --package minimal-winit
minimal-winit v0.1.0 (C:\Users\jay\projects\pixels\examples\minimal-winit)
└── env_logger v0.9.0
    ├── atty v0.2.14
    │   └── winapi v0.3.9
    ├── humantime v2.1.0
    ├── log v0.4.14
    │   └── cfg-if v1.0.0
    ├── regex v1.5.4
    │   ├── aho-corasick v0.7.18
    │   │   └── memchr v2.4.1
    │   ├── memchr v2.4.1
    │   └── regex-syntax v0.6.25
    └── termcolor v1.1.2
        └── winapi-util v0.1.5      <--
            └── winapi v0.3.9
```

And it compiles fine for me locally and on CI. Maybe you need to run `cargo clean`?

**Comment by parasyte** [comment]
Another option is using the GLES 3 backend, either by setting an environment variable: `WGPU_BACKEND=gl` or by hardcoding it in your builder.

**Comment by parasyte** [comment]
@Lucky4Luuk were you able to try any of the suggestions in this thread?

**Comment by Lucky4Luuk** [comment]
Hey, sorry for the late response, I haven't been able to try much yet. All I did was attempt to specify the GL backend for wgpu in the pixel builder, but that give me an "Adapter not found" error. Tomorrow night I'll finally have some time to check your suggestions, thanks in advance!

**Comment by parasyte** [comment]
This could have the same root cause as #255

**Comment by parasyte** [comment]
Closing this one because I haven't heard from OP in a while, and this is probably going to be resolved by updating the driver.
