### ISSUE TITLE
ability to set the background/clear color.

### ISSUE THREAD

**Issue by Lokathor** [parasyte/pixels#235]
The buffer supports texture formats with alpha, but the backdrop color _behind_ the buffer does not appear to be easily configurable, if it can be adjusted at all (i dunno how wgpu works, maybe `render_with` can do it somehow). I would expect a basic setter function, similar to changing the buffer size.

**Comment by parasyte** [comment]
Implemented in #236

**Comment by parasyte** [comment]
Oh, now that I re-read your comment, it looks like you want to change the clear color at runtime. I don't see why not, I just didn't think to add a setter on the primary `Pixels` struct, just on the builder. Is that something you would want to use?

**Comment by Lokathor** [comment]
Yes. I'm making an image previewer tool to go with `imagine` and if you drag and drop a new file into the window it switches the image. However, each image might declare its own background color, so the background should be adjustable.

**Comment by parasyte** [comment]
The [new commit](https://github.com/parasyte/pixels/pull/236/commits/dab0674150b309c5496d62c1164e83443f0915da) should solve that. Let me know if the PR needs anything else.
