### ISSUE TITLE
[Bug] wgpu tries to load Vulkan on GPU that doesn't support it

### ISSUE THREAD

**Issue by alexmozaidze** [parasyte/pixels#237]
I was trying to load one of the examples but it crashed with an error message stating that it can't load Vulkan
```
[2021-12-05T15:15:24Z WARN  wgpu_hal::vulkan::instance] create_instance: VkError(ERROR_INCOMPATIBLE_DRIVER)
Error: AdapterNotFound
```
My integrated video card only supports OpenGL but it tries to load Vulkan anyway.
I asked about it in the Game Development In Rust Discord server and they pointed out that the GL backend was off on this line. Is this intentional?
https://github.com/parasyte/pixels/blob/b15854b4d1c55023e621c343ed9485863c41e649/src/builder.rs#L55

**Comment by parasyte** [comment]
> I asked about it in the Game Development In Rust Discord server and they pointed out that the GL backend was off on this line. Is this intentional?

The design is intentional. You can override the default either with the `WGPU_BACKEND=gl` environment variable, or by hardcoding your own with the builder API: https://docs.rs/pixels/latest/pixels/struct.PixelsBuilder.html#method.wgpu_backend

```rust
let pixels = PixelsBuilder::new(WIDTH, HEIGHT, surface_texture)
    .wgpu_backend(pixels::wgpu::Backends::GL)
    .build()?;
```

**Comment by alexmozaidze** [comment]
I force-enabled gl and it appears that my GPU doesn't have enough features to be supported by wgpu, which kinda sucks.
