### ISSUE TITLE
Crash on Mac / Custom Shader

### ISSUE THREAD

**Issue by markusmoenig** [parasyte/pixels#258]
Hi, great job!

On my M1 Max I get a crash in the custom shader example. Attached below.

btw; wouldn't it be nice to have hardware backed offline buffer which one could blit to the main texture via hardware ? That would open up so many possibilities.

[2022-01-21T04:58:10Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `pixels_command_encoder`
    In a set_scissor_rect command
    Invalid ScissorRect parameters

**Comment by parasyte** [comment]
Hello!

I only have an Intel MBP, but I can try to reproduce this. Note that "Invalid ScissorRect" is something I have seen quite a few times. It usually emerges as a result of differences between the surface texture (what is displayed on screen) and the surface itself (a window). If you have any tips for reproducing, that might be helpful!

Also, the hardware backed buffer sounds like #170 - it just needs some design and an implementation. 😄

**Comment by markusmoenig** [comment]
Thanks for the quick reply. I only launched the example from the command line via "cargo run --release --package custom-shader". I am a novice to Rust / wgpu as I just transitioned from Swift / Metal.

BTW; how can I see which backend wgpu is using ?

Thanks so much.

**Comment by parasyte** [comment]
> BTW; how can I see which backend wgpu is using ?

This can be done with an environment variable:

```
RUST_LOG='wgpu_core::instance=info' cargo run --package custom-shader --release --no-default-features
```

The `--no-default-features` allows all log levels, so it isn't recommended for "real release" builds, but it's handy for debugging.

And I can easily reproduce, so I'll look at this when I get some free time!
