### ISSUE TITLE
egui & imgui examples seem to be extremely laggy

### ISSUE THREAD

**Issue by ioncodes** [parasyte/pixels#269]
I'm interested in using this library and therefore checked out the provided examples. As of writing this issue, all examples except `minimal-egui` and `imgui-winit` work flawlessly. Is this a known issue? I'm running this under high-end hardware.
This behaviour persists across both debug and release mode.

EDIT: I've noticed there is another example called `imgui-winit` that has the same issue. I have updated the issue accordingly.

**Comment by parasyte** [comment]
You'll need to provide more information to help diagnose the issue.

First, exactly what do you mean by "extremely laggy"? Is it rendering frames late, like you like a button and there is some delay before the reaction is shown on screen? Or are you using a high frame rate display and the rendering is stuck at a lower frame rate? I could imagine 60fps on a 240 hz display could feel "extremely laggy". Or is the issue something else entirely? Can you capture the behavior on video?

In any case, no this not a known issue. First time I've heard of it!

Have you tried any of the troubleshooting steps documented in the README? Particularly, the examples all run on a low power GPU if available. The troubleshooting steps describe how to switch to a high power GPU, or even select the GPU by name. These can also be hard coded or programmatically controlled in your project, if this is the issue.

What platform are you using? OS? GPU(s)? Driver versions? If you are using an NVidia GPU, do you have windowed GSYNC enabled, and have you tried changing it to full screen only or disabling it for specific executables like these examples?

Unfortunately this issue raises a lot more questions than answers. I don't know anything at all about your environment, your expectations, or your observations. Any precise details you can provide can help narrow down what is happening here.

**Comment by ioncodes** [comment]
Thanks for your swift response! Apologies for not including more information.

By "extremely laggy" I mean that the EGUI/IMGUI UI responds very slowly to input events. Additionally, when I move around the window it also seems to be very choppy. Here's an example video:

https://user-images.githubusercontent.com/18533297/161693891-a52a9809-793e-404c-9540-8d0d59702f61.mp4

Unfortunately, you can't really make out the choppy feel when moving the window, however, the overlay lagging behind seems to be fairly apparent. It looks like the actual rectangle that is being drawn on screen is lag-free.
My knowledge is quite limited when it comes to this library and I'm not quite sure how to patch it to display the actual FPS in the window, but I will have a look as soon as I have time and update you accordingly. That being said, I'm currently on a 144hz display.

I have tried the troubleshooting steps, although it needs to be said that I have only one GPU anyways. I am currently running a Ryzen 9 5950x and a 3080Ti if that information could help you diagnosing this problem.
I am running this example on Windows 11 Pro Build 22000 with the GeForce Game Ready Driver version 512.15 (seems to be the latest as of writing this comment). GSYNC is disabled as I don't have a compatible screen.

I hope I was able to answer all (or rather, almost all) questions.

**Comment by parasyte** [comment]
Thanks for the additional info and the video! I agree it looks like it is performing poorly. Although it is running in debug mode (I know you said release mode looks the same). Debug mode is notoriously slow. Rewriting the pixel buffer in debug mode is unlikely to ever hit your target refresh rate. I'm using a 5900X + RTX 3090 and this demo tops out at 68 fps in debug mode, here. That said, it's still much more responsive than what your video shows.

You can add this patch to periodically print the frame rate:

```patch
diff --git a/examples/imgui-winit/src/main.rs b/examples/imgui-winit/src/main.rs
index 9131595..4d6babf 100644
--- a/examples/imgui-winit/src/main.rs
+++ b/examples/imgui-winit/src/main.rs
@@ -4,6 +4,7 @@
 use crate::gui::Gui;
 use log::error;
 use pixels::{Error, Pixels, SurfaceTexture};
+use std::time::{Duration, Instant};
 use winit::dpi::LogicalSize;
 use winit::event::{Event, VirtualKeyCode};
 use winit::event_loop::{ControlFlow, EventLoop};
@@ -55,6 +56,10 @@ fn main() -> Result<(), Error> {
     // Set up Dear ImGui
     let mut gui = Gui::new(&window, &pixels);

+    // Bookkeeping for fps counter
+    let mut frame_count = 0;
+    let mut last_second = Instant::now();
+
     event_loop.run(move |event, _, control_flow| {
         // Draw the current frame
         if let Event::RedrawRequested(_) = event {
@@ -83,6 +88,14 @@ fn main() -> Result<(), Error> {
                 *control_flow = ControlFlow::Exit;
                 return;
             }
+
+            frame_count += 1;
+            let now = Instant::now();
+            if now.duration_since(last_second) >= Duration::from_secs(1) {
+                println!("fps: {frame_count}");
+                frame_count = 0;
+                last_second = now;
+            }
         }

         // Handle input events
```

Running in release mode, I easily hit the display refresh rate with room to spare. With an additional patch to disable vertical sync, this demo runs at just over 1,200 fps (yes, one thousand, two hundred frame per second. That was not a typo.)

```patch
@@ -48,13 +49,19 @@ fn main() -> Result<(), Error> {
     let mut pixels = {
         let window_size = window.inner_size();
         let surface_texture = SurfaceTexture::new(window_size.width, window_size.height, &window);
-        Pixels::new(WIDTH, HEIGHT, surface_texture)?
+        pixels::PixelsBuilder::new(WIDTH, HEIGHT, surface_texture)
+            .present_mode(pixels::wgpu::PresentMode::Immediate)
+            .build()?
     };
     let mut world = World::new(WIDTH, HEIGHT);

```

In theory, this will give you the lowest possible latency. But it is terribly inefficient.

----

Another piece of the puzzle might be revealed with some extra logging. You can enable logging by setting the `RUST_LOG` environment variable and passing the `--no-default-features` flag to Cargo. A useful place to start is with `RUST_LOG='wgpu_core::instance=info'`:

```
$ RUST_LOG='wgpu_core::instance=info' cargo run --release --package imgui-winit --no-default-features
    Finished release [optimized] target(s) in 0.10s
     Running `target\release\imgui-winit.exe`
[2022-04-06T07:20:46Z INFO  wgpu_core::instance] Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce RTX 3090", vendor: 4318, device: 8708, device_type: DiscreteGpu, backend: Vulkan }
fps: 181
fps: 181
fps: 180
fps: 180
fps: 180
fps: 180
```

If this log line gives you anything other than your 3080Ti and `device_type: DiscreteGpu, backend: Vulkan`, then this could be an indicator of the issue.

**Comment by parasyte** [comment]
@ioncodes Do you have any update on your experience following the suggestions above?

**Comment by ioncodes** [comment]
Apologies for the long wait! I just gave this another shot using your patch. It seems to always hit 25 FPS, both in Debug and Release mode.

![image](https://user-images.githubusercontent.com/18533297/165132586-21dcdc3f-c43b-47c1-b7ff-6307a54d0b63.png)

However, it looks like I was able to find the culprit with your assistance. When setting the `RUST_LOG` variable as suggested, the executable prints `[2022-04-25T16:30:17Z INFO  wgpu_core::instance] Adapter Dx12 AdapterInfo { name: "Microsoft Basic Render Driver", vendor: 5140, device: 140, device_type: IntegratedGpu, backend: Dx12 }` which is what I assume a software renderer. I have yet to figure out why it's not respecting the `WGPU_POWER_PREF` variable. I tested this on another machine with close to the same specifications, and it works so it seems to be a setup issue on my end!

I'll be closing this issue due to my findings mentioned above.

**Comment by parasyte** [comment]
Widening the log filter to `RUST_LOG="trace"` will give you highly detailed output, hopefully helping pinpoint why the expected device is not selected. You can also try the [`wgpu-info`](https://github.com/gfx-rs/wgpu/tree/master/wgpu-info) example to get more info. If you find anything relevant, please file an [issue on `wgpu`](https://github.com/gfx-rs/wgpu/issues) so it can be addressed.
