### ISSUE TITLE
Smooth pixels

### ISSUE THREAD

**Issue by nathanosoares** [parasyte/pixels#277]
Is it possible to create a smooth pixel layer?

I'm trying to draw a border around my video, but it looks pretty rough.

![image](https://user-images.githubusercontent.com/7758072/172611031-367ab1bf-0b41-4266-ace9-4a8d5ca88d70.png)

I'm looking for the smoothest like this:
![image](https://user-images.githubusercontent.com/7758072/172611199-0e7c0a80-5754-4179-af8c-025cee114b85.png)

**Comment by parasyte** [comment]
My guess is that you are drawing the border at one resolution and displaying it at another. The best way to solve this is to scale the pixel buffer in a pass separate from the border. E.g. by putting the border into its own texture and rendering it over the scaled pixel buffer.

Apart from a generic description like this, I cannot really provide any more details without knowing how you came to the result in the screenshot, or what your graphics stack looks like.

**Comment by nathanosoares** [comment]
I don't know how to scale the pixel buffer
here is my code https://github.com/nathanosoares/rust-floating-facecam

I am creating a 300x300 window and a Pixels instance with SurfaceTexture also 300x300

https://github.com/nathanosoares/rust-floating-facecam/blob/main/src/lib.rs#L127-L132

**Comment by parasyte** [comment]
Scaling is performed automatically if you have a difference between the physical pixel buffer size and the surface size.

The zoomed detail looks more like you are missing antialiasing and alphablending, though. Is this where you are adding the border? https://github.com/nathanosoares/rust-floating-facecam/blob/b49d22b935b20c9670b19c6904e773d72ea6fc02/src/lib.rs#L71-L78 If it is, that's where you need to blend the pixel colors... How you do it is up to you. I might suggest looking at some literature that discusses pixel coverage and blending.

I'm sure there are much better sources available, but here are some lecture slides that go over the basics:

- http://graphics.cs.cmu.edu/courses/15-463/2007_fall/Lectures/blending.pdf
- https://www.cs.cornell.edu/courses/cs4620/2009fa/lectures/15aa-comp.pdf

And of course, wikipedia: https://en.wikipedia.org/wiki/Alpha_compositing

**Comment by parasyte** [comment]
Without any more input from OP in a while, I'm going to close this. If you need more assistance, please open a [new discussion](https://github.com/parasyte/pixels/discussions/new)!
