### ISSUE TITLE
Egui 0.18.1 is not supported by minimal-egui example (it's built with egui 0.17)

### ISSUE THREAD

**Issue by Roxfall** [parasyte/pixels#278]
The breaking change is egui renamed its ClippedMesh to be ClippedPrimitive in 18.0, which then messes up the render function in the example gui.rs around line 86.

I don't know the best way to reconcile these libs.

https://github.com/emilk/egui/blob/master/CHANGELOG.md

**Comment by parasyte** [comment]
While not technically a blocker for that example, I do need https://github.com/emilk/egui/pull/1660 (and probably https://github.com/emilk/egui/pull/1684 and https://github.com/emilk/egui/pull/1704) so I've been waiting for the next release before doing any more work on it. I won't reject a PR if one comes my way, though.

**Comment by parasyte** [comment]
Found some time to do the upgrade, so this should be fixed very soon.
