### ISSUE TITLE
Custom shader example panics when minimized

### ISSUE THREAD

**Issue by dbalsom** [parasyte/pixels#282]
[2022-06-19T22:31:57Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension X is zero

~~~~
OS: Windows 10
GPU: 3080Ti

**Comment by parasyte** [comment]
Hi! If you are using Windows, this is most likely https://github.com/rust-windowing/winit/issues/2015

We have a workaround for this issue in the core. You will have to do something similar in your application as well: https://github.com/parasyte/pixels/blob/af821c9e49f107b9d3fcaf0f2393364f3abf7ba1/src/lib.rs#L314-L316

And now that I look more closely, the `custom-shader` example doesn't have this logic. I will check if/why it works on Windows shortly!
