### ISSUE TITLE
Tao support ?

### ISSUE THREAD

**Issue by markusmoenig** [parasyte/pixels#298]
Hi,

is it possible to get Tao support and a small example same as you did for winit ? winit has some shortcomings if you want to create a shipping Desktop app, like missing native menu bars. Tao is a fork of winit and has these and other things....

**Comment by parasyte** [comment]
Yeah! I have used `tao` on a few projects. The last time I poked around at it, the API still resembled `winit` enough that using the basics should look very similar. I think adding an example for it would be a good idea.
