### ISSUE TITLE
Quicker way to set/clear the entire pixel buffer?

### ISSUE THREAD

**Issue by pixelgaming579** [parasyte/pixels#318]
My current rendering process doesn't loop over every pixel in the buffer, so it can't set/clear every pixel that doesn't need to be set. If I don't clear the buffer every time before rendering, I get leftover data from the previous render. The fastest method I have found for this is `pixels.get_frame_mut().copy_from_slice(vec![0; 4 * s.width as usize * s.height as usize].as_mut_slice());`, but this still slows the program down considerably. Is there a quicker way to do this? or will a new function need to be added?

**Comment by parasyte** [comment]
I see you closed this and I assume it’s because you found a suitable answer. The fastest way to clear the buffer is:

```rust
// clear the frame to transparent black
frame.fill(0);
```

Or if you want to use a specific color:

```rust
// clear the frame to opaque black
let pixel_count = frame.len() / 4;
frame.copy_from_slice(&[0, 0, 0, 255].repeat(pixel_count)]);
```
