### ISSUE TITLE
Android example

### ISSUE THREAD

**Issue by Randommist** [parasyte/pixels#367]
I think the project needs example code to run an android application. I've already managed to rewrite the `minimal-winit` example to make it work on Android. I used `winit` features `android-native-activity` and `cargo-apk` tool. In the future I might make a tetris game. Therefore, I want to discuss whether such an example is needed for `Pixels`

**Comment by parasyte** [comment]
Hi! I don't have an Android device, but I would gladly accept a PR that introduces an example that can run on Android. It would only have to pass the minimum CI requirements.
