### ISSUE TITLE
No possibility of changing the surface `PresentMode` without recreating the whole `Pixels` instance

### ISSUE THREAD

**Issue by Kanabenki** [parasyte/pixels#372]
Pixels version: 0.13.0

I'm working on a project in which I would like to be able to toggle vsync on/off after my `Pixels` instance has been initialized. Currently, the only solution I found was to recreate my `Pixels` instance with this setting changed, using the `Option<Pixels>` workaround mentioned in #238 (it seems that problem in particular has been fixed on the main branch though)

Would it be possible for example to add some `enable_vsync` and `set_present_mode` methods on `Pixels`, similarly to what is currently exposed in `PixelsBuilder`. Those would set the present mode and reconfigure the wgpu surface. If that seems an ok proposal, I can submit a PR :slightly_smiling_face:

**Comment by parasyte** [comment]
Hi!

That seems like a feature that might be useful for some scenarios. I'd accept a PR.

I would caution about trying to simplify `wgpu` presentation modes to just a boolean VSync flag. We've had some problems from doing this in the past: #263. Particularly, VSync does not exist in web targets.

**Comment by Kanabenki** [comment]
> I would caution about trying to simplify wgpu presentation modes to just a boolean VSync flag. We've had some problems from doing this in the past: https://github.com/parasyte/pixels/issues/263. Particularly, VSync does not exist in web targets.

Indeed I saw this issue, for my use case this is not a problem though (I'm targeting desktop only). I'll submit a PR mirroring the builder API so that it can be set with the exact mode or a simple toggle, unless you plan to remove `enable_vsync` on the builder in the future.

> Hmm, that is definitely not the case! https://github.com/parasyte/pixels/issues/238 is still open for a reason.

My bad ! I saw 932507818812c417787ce80aa579a43ba0462ba9 and thought it fixed that but it seems there are still some problems then ^^

**Comment by parasyte** [comment]
> I saw [9325078](https://github.com/parasyte/pixels/commit/932507818812c417787ce80aa579a43ba0462ba9) and thought it fixed that but it seems there are still some problems then ^^

Ah, yes. That's in an experimental branch! It can potentially fix the problem, but it's incomplete.
