### ISSUE TITLE
Using pixels with eframe

### ISSUE THREAD

**Issue by sllide** [parasyte/pixels#384]
Hello, i started using rust not too long ago and settled on egui and pixels to toy around in. But i was wondering if it would be possible to use eframe instead of raw winit, i like eframe more. I have a feeling that it might be possible, but i'm too much of a noob with rust to deduct if that is indeed the case.

So could I have an answer to that, and if you are feeling really swell, give some pointers or a basic example on how to get that up and running? Given that it is indeed possible.

Thanks a bunch!

**Comment by dbalsom** [comment]
> For instance, when you want to add a native system menubar (especially for macOS) 

do you recommend a particular crate for native menubars supporting macOS? My emulator works fine on macos but the completely blank menubar bugs me.

**Comment by parasyte** [comment]
@dbalsom There are two that I know of:

- [`muda`](https://crates.io/crates/muda) is a spinoff from `tao`.
- [`menubar`](https://crates.io/crates/menubar) looks ... aspirational.

I haven't used either. Our `minimal-tao` example has a native menubar provided by the older version of `tao`, before the functionality was split off into `muda`.

**Comment by sllide** [comment]
Hi, thanks for the reply. Sorry for my late reply.
I have since found a framework that better fits my needs.

Do keep up the good work!
