### ISSUE TITLE
Add a method to translate mouse coordinates to pixel buffer coordinates

### ISSUE THREAD

**Issue by parasyte** [parasyte/pixels#39]
This came up in #37; users will want to use mouse interactions with their favorite window manager, and `pixels` needs to provide a method for converting coordinates from window surface texture space to pixel buffer texture space. This is especially tricky after resizing the window, since the pixel buffer texture is always scaled to the nearest integer size, leaving a border if necessary.

**Comment by DhruvDh** [comment]
Hello,

Maybe this feature belongs in a Windowing crate? For instance, `winit` seems to have a `CursorMoved` event that returns a `PhysicalPosition` struct to represent mouse co-ordinates which can be converted to position in terms of logical pixels (after accounting for DPI and such) via the [to_logical](https://docs.rs/winit/0.20.0/winit/dpi/struct.PhysicalPosition.html#method.to_logical) function.

**Comment by parasyte** [comment]
It does seem at first that leaving this to the window manager is the right approach. But because the `pixels` crate is maintaining integer scaling, it will add a border that the lower level cannot handle without some help.
