### ISSUE TITLE
Safety dance!

### ISSUE THREAD

**Issue by parasyte** [parasyte/pixels#40]
See [Rust Safety Dance](https://github.com/rust-secure-code/safety-dance/) - it's cute!

There is one bit of `unsafe` code, and that's the `Deref` impl for the `Spirv` type: https://github.com/parasyte/pixels/blob/e0225c145d2972b8803e64088fad9de0951caf02/src/macros.rs#L34-L36

Making `pixels` 100% safe Rust is kind of a hilarious challenge in an ironic way, considering it sits on top of a mountain of `unsafe`.

**Comment by Huanzo** [comment]
#43 Here's my take on this :D Its 100% safe now but it comes at a slight startup performance penalthy. We should find out if it is noticable/matters much.
