### ISSUE TITLE
greedy meshing?

### ISSUE THREAD

**Issue by suprohub** [parasyte/pixels#404]

**Comment by parasyte** [comment]
Is there a question, here?

**Comment by suprohub** [comment]
Yes

**Comment by suprohub** [comment]
And what about winit 0.30? I created fork where winit 0.30.5 and wgpu 22.1.0

**Comment by parasyte** [comment]
What's the question wrt greedy meshing?

`winit` 0.30 was discussed recently in #403. `wgpu` 22 has an open PR in #402.

**Comment by suprohub** [comment]
> What's the question wrt greedy meshing?
> 
> `winit` 0.30 was discussed recently in #403. `wgpu` 22 has an open PR in #402.

Can we implement greedy meshung?

**Comment by parasyte** [comment]
`pixels.context()` and `pixels.adapter()` give you access to all of the `wgpu` internal state. You can use it to implement any graphics technique you like.
