### ISSUE TITLE
possibility of reducing number of frames lost per second because of Pixels::render()

### ISSUE THREAD

**Issue by mTvare6** [parasyte/pixels#405]
The `minimal-winit` usually runs at about 140 loops per second in my laptop and when commenting out `pixels.render()` in `main.rs:58-63`, the LPS jumps to about 8000.
Other libraries like Raylib also generally have much higher FPS in minimal examples(but I haven't tested with drawing textures though.) 
I am building a simulation based on Verlet Integration and have a small timestep makes the quality bad and I have to use smaller constant multiplier to effects to keep quality which makes it take longer time. Is there something I can do to get higher LPS?

PS: I am aware this isn't an apples to apples comparison, but just wanted to know if I'm missing something.(The FPS seems independant of texture size too)
PS PS: Or is it possible to set a constant framerate by some means?(Raylib can)

**Comment by parasyte** [comment]
I don't know what the "loops per second" metric is attempting to measure. The part of rendering that takes the most time is waiting for the display's vertical blank period during `present` with [`AutoVsync`](https://docs.rs/wgpu/latest/wgpu/enum.PresentMode.html#variant.AutoVsync).

You can just turn it off to render as fast as possible (don't synchronize to the display's native frame rate): `pixels.enable_vsync(false);`

Note that you should not be drawing after every physics step. But rather run multiple steps per video frame. This is what the [`game-loop`](https://crates.io/crates/game-loop) crate does, based on the seminal ["Fix Your Timestep!"](https://gafferongames.com/post/fix_your_timestep/) Using VSync is important for avoiding frame tearing. And these techniques can be used together to get fine grained physics with the native frame rate.
