### ISSUE TITLE
Running the winit example fails

### ISSUE THREAD

**Issue by SRugina** [parasyte/pixels#59]
I was interested in experimenting with this crate, but sadly couldn't get the example winit or my own attempts to show anything other than a black window. When running the winit example, I get the following error:

```
[2020-04-04T18:12:59Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
[2020-04-04T18:12:59Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
[2020-04-04T18:12:59Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadDrawable (invalid Pixmap or Window parameter)",
        error_code: 9,
        request_code: 149,
        minor_code: 4,
    }
```

**Comment by parasyte** [comment]
I _think_ this is a problem with how I've specified dependencies, but I will check it out in a bit.

Also I've been meaning to redo how examples are built. I ended up with the current hack (in the master branch) because I didn't want to pollute the crate with unnecessary dependencies, but I still wanted to use the `cargo --example` command. I'm thinking now I need to just break all examples into separate crates...

**Comment by parasyte** [comment]
I don't think I'll be able to reproduce this myself. Everything still works correctly on macOS and Windows. But I did find similar reports for X11 on other projects:

* https://github.com/rust-windowing/winit/issues/748
* https://github.com/hecrj/iced/issues/70#issuecomment-558872369
* https://github.com/Kethku/neovide/issues/175#issuecomment-596082317
* https://www.reddit.com/r/linuxquestions/comments/eaoiqo/x_error_of_failed_request_baddrawable_when/

See if any of the workaround provided help. Unfortunately, I don't think this is a bug in this crate, but an issue with your specific environment or setup.

**Comment by SRugina** [comment]
Yep, seems to be an issue with my system. Hopefully using a different distro will fix it - thanks for the links though.
