### ISSUE TITLE
Regression: setting wgpu backend is not possible in 0.0.3

### ISSUE THREAD

**Issue by parasyte** [parasyte/pixels#75]
The backend is now hardcoded: https://github.com/parasyte/pixels/blob/809d3f6dd9c1c47204c0cc3eac15d814bac731ef/src/lib.rs#L431 (used to be a child of `RequestAdapterOptions`). This needs a new builder method and probably cutting a new release soon.

**Comment by Aeledfyr** [comment]
I believe that this should be closed, as #78 added a builder method for this.  I guess github didn't recognize the second issue mention.
