### ISSUE TITLE
AdapterNotFound on Pixel::new

### ISSUE THREAD

**Issue by harrysarson** [parasyte/pixels#86]
Hi, I am trying to run the `minimal-winit` example (on git master) and I get 

```
Error: AdapterNotFound
```

I looked at #83 and #29 and tried `WINIT_UNIX_BACKEND=x11 cargo run` but got the same error. Installing [xorg-server](https://www.archlinux.org/packages/?name=xorg-server) and [libx11](https://www.archlinux.org/packages/extra/x86_64/libx11/) but neither helped.

```
$ echo $XDG_SESSION_DESKTOP
gnome
 
$ echo $XDG_SESSION_TYPE        
wayland
 
$ uname -a 
Linux archlinux 5.4.43-1-lts #1 SMP Wed, 27 May 2020 23:42:34 +0000 x86_64 GNU/Linux
```

**Comment by parasyte** [comment]
Your host needs to support Vulkan, and you may be missing drivers, or running on a very old driver. Support for OpenGL is currently a work in progress.

**Comment by harrysarson** [comment]
Hi thanks the makes sense :). I will look into my drivers re Vulcan. Is there a way of getting more debugging info out of pixel or winit?

**Comment by parasyte** [comment]
Yes! The examples use a crate called `env_logger` which allows you to control debug logs through the [`RUST_LOG`](https://docs.rs/env_logger/0.7.1/env_logger/#enabling-logging) environment variable. You can read more about it in the linked docs.

The examples also have a feature set on the `log` crate that limits the log level in release builds. So for debug logs, you should build the debug profile. Here’s a simple example:

```
$ RUST_LOG=trace cargo run —package=invaders
```

**Comment by harrysarson** [comment]
Thanks, I will give that a try next time I have some time. I will close for now and see if I can get it work.

Thanks for you help

**Comment by harrysarson** [comment]
In case anyone else ends up here: As per the arch [vulkan docs](https://wiki.archlinux.org/index.php/Vulkan) I installed [vulkan-intel](https://www.archlinux.org/packages/?name=vulkan-intel) and the exampe now runs. :+1:
