### ISSUE TITLE
Add option for wgpu::PresentMode::Fifo

### ISSUE THREAD

**Issue by p4ddy1** [parasyte/pixels#88]
Hi. It would be nice to have the option to use wgpu::PresentMode::Fifo for V-Sync to be able to limit the execution speed of the event loop. Is there a reason that enabling V-Sync defines explicitly Mailbox as PresentMode?

**Comment by parasyte** [comment]
My initial intention with #57 was to expose the wgpu types. It was closed with a contribution in #78. I'm open to continuing to improve the public API.
