### ISSUE TITLE
Feature request: additional TextureFormats for pixels.get_frame()

### ISSUE THREAD

**Issue by Walther** [parasyte/pixels#91]
Thank you for the great project!

Just something I bumped into in a personal project, feel absolutely free to say this would be out of scope or similar!

I've been writing a little raytracer lately. So far, I had only written out .png image files when the whole render was ready, but I started looking into having an iterative display of the progress as a gui window.

Looking at example code:

https://github.com/parasyte/pixels/blob/master/examples/minimal-winit/src/main.rs#L49

https://github.com/parasyte/pixels/blob/master/examples/minimal-winit/src/main.rs#L111-L112

I was able to create a minimum viable example, where each `draw()` call generates a new sample for each pixel and blends them in with the existing pixels. However, because the `get_frame()` uses a `wgpu::TextureFormat::Rgba8UnormSrgb`, each individual color component only has u8 aka 256 possible values - converting from that back into my raytracer's float-based colors for blending and back into u8's for the buffer at every draw seems to cause quite a bit of quality loss over multiple iterations.

It seems like `wgpu` also has [a `Rgba32Float` texture format](https://docs.rs/wgpu/0.5.0/wgpu/enum.TextureFormat.html#variant.Rgba32Float). Would it be possible to expose that from `pixels`? This would allow people to use float-based buffers in addition to the u8-based ones 🙂

Of course another workaround would be for me to store a separate float buffer, do the blending with that, and only use pixels with its u8 frames for output.

(EDIT: i may have also goofed and my artefacts may also come from another part of the code, but leaving this issue up because of the possibility of removing the extra buffer workaround in the future)

**Comment by parasyte** [comment]
Hi! You can set the texture format using the [texture_format](https://docs.rs/pixels/0.0.4/pixels/struct.PixelsBuilder.html#method.texture_format) builder method. You can't change the texture type for the swap chain's destination texture, but you can use this to change the format of the data that you will use to populate the source texture buffer.
